// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt_Y6LgAtzuqmAn-6dlbbAEP_UXGzFMfc',
    appId: '1:302950149301:web:5d6ce0c7019d50acf8e2fc',
    messagingSenderId: '302950149301',
    projectId: 'sledge-9a90a',
    authDomain: 'sledge-9a90a.firebaseapp.com',
    storageBucket: 'sledge-9a90a.firebasestorage.app',
    measurementId: 'G-XH875VP56R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGs1fpZq6a7AfnjA1KDoJ2Mz5Sk9NJ6GQ',
    appId: '1:302950149301:android:64ba3abe378585b2f8e2fc',
    messagingSenderId: '302950149301',
    projectId: 'sledge-9a90a',
    storageBucket: 'sledge-9a90a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpiDgFZKR2hda-DdtSwh3u-9oc4JJe-yo',
    appId: '1:302950149301:ios:212d326be9f9d220f8e2fc',
    messagingSenderId: '302950149301',
    projectId: 'sledge-9a90a',
    storageBucket: 'sledge-9a90a.firebasestorage.app',
    iosBundleId: 'com.example.sledgeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpiDgFZKR2hda-DdtSwh3u-9oc4JJe-yo',
    appId: '1:302950149301:ios:212d326be9f9d220f8e2fc',
    messagingSenderId: '302950149301',
    projectId: 'sledge-9a90a',
    storageBucket: 'sledge-9a90a.firebasestorage.app',
    iosBundleId: 'com.example.sledgeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBt_Y6LgAtzuqmAn-6dlbbAEP_UXGzFMfc',
    appId: '1:302950149301:web:703f41254e8df5aff8e2fc',
    messagingSenderId: '302950149301',
    projectId: 'sledge-9a90a',
    authDomain: 'sledge-9a90a.firebaseapp.com',
    storageBucket: 'sledge-9a90a.firebasestorage.app',
    measurementId: 'G-PZBJSRCDHG',
  );
}
