import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart'; // Import Firebase Core
import 'package:sledge_app/pages/custom_home_page.dart';
import 'package:sledge_app/pages/login_page.dart';
import 'package:sledge_app/pages/registration_page.dart';

// Ensure you have a firebase_options.dart file generated by FlutterFire CLI
// To generate it, run: flutterfire configure
import 'firebase_options.dart';

void main() async { // main function must be async
  WidgetsFlutterBinding.ensureInitialized(); // This must be the first line in main()
  await Firebase.initializeApp( // Corrected spelling of Firebase and added options
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Sledje Mobile App', // Added a title for the app
      initialRoute: '/', // Set initial route to login page
      routes: {
        '/': (context) => const LoginPage(),
        '/home': (context) => const CustomHomePage(),
        '/register': (context) => const RegistrationPage(),
      },
    );
  }
}
